# todo: swagger automated doc for Restaurant route client side

#this is basic example for yaml swagger doc with get request
openapi: 3.0.1
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:3001/
tags:
  - name: Restaurant Client Side
    description: All routes for restaurant client side
paths:
  /restaurants:
    get:
      tags:
        - Restaurant Client Side
      summary: Retrieve all restaurants
      responses:
        200:
          description: A list of all restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Restaurants"
  /restaurants/{id}:
    get:
      tags:
        - Restaurant Client Side
      summary: Retrieve a specific restaurant by ID
      parameters:
        - name: id
          in: path
          description: ID of the restaurant to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A single restaurant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurants"
        404:
          description: Restaurant not found
          content: {}
  /restaurants/{id}/products:
    get:
      tags:
        - Restaurant Client Side
        - Restaurant Seller Side
      summary: Get restaurant's menu
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the restaurant
          schema:
            type: integer
      responses:
        '200':
          description: A list of products for the specified restaurant
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '404':
          description: The specified restaurant was not found

  /restaurants/recommends:
    get:
      tags:
        - Restaurant Client Side
      summary: Retrieve recommended restaurants
      responses:
        200:
          description: A list of recommended restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Restaurants"

components:
  schemas:
    # Schema for ProductInput object
    ProductInput:
      type: object
      properties:
        id:
          type: integer
          description: The restaurant's ID
        name:
          type: string
          description: The name of the product.
        description:
          type: string
          description: The description of the product.
        price:
          type: number
          description: The price of the product.
          format: double

    # Schema for Restaurant object
    Restaurants:
      type: object
      properties:
        id:
          type: int
          description: The ID of the restaurant.
        title:
          type: string
          description: The name of the restaurant.
        address:
          type: string
          description: The address of the restaurant.
        image:
          type: string
          description: The link to the image of the restaurant.
        company_id:
          type: int
          description: ref of companies.
      required:
        - id
        - title
        - address
        - image
        - company_id

    # Schema for RestaurantInput object
    RestaurantInput:
      type: object
      properties:
        name:
          type: string
          description: The name of the restaurant.
        address:
          type: string
          description: The address of the restaurant.
        phone_number:
          type: string
          description: The phone number of the restaurant.

    # Schema for Product object
    Products:
      type: object
      properties:
        id:
          type: int
          description: The ID of the product.
        title:
          type: string
          description: The name of the product.
        description:
          type: string
          description: The description of the product.
        image:
          type: array
          description: array of links to images.
        price:
          type: number
          description: The price of the product.
          format: double
        restaurant_id:
          type: int
          description: The ID of the restaurant this product belongs to.

      required:
        - id
        - title
        - description
        - image
        - price
        - restaurant