openapi: 3.0.1
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:3001/
tags:
  - name: Restaurant Client Side
    description: All routes for restaurant client side
paths:
  /restaurants:
    get:
      tags:
        - Restaurant Client Side
      summary: Retrieve all restaurants
      responses:
        200:
          description: A list of all restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Restaurant"
  /restaurants/{id}:
    get:
      tags:
        - Restaurant Client Side
      summary: Retrieve a specific restaurant by ID
      parameters:
        - name: id
          in: path
          description: ID of the restaurant to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A single restaurant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
        404:
          description: Restaurant not found
          content: {}
  /restaurants/recommends:
    get:
      tags:
        - Restaurant Client Side
      summary: Retrieve recommended restaurants
      responses:
        200:
          description: A list of recommended restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Restaurant"
components:
  schemas:
    Restaurant:
      type: object
      properties:
        id:
          type: integer
          description: The restaurant's ID
        title:
          type: string
          description: The restaurant's title
        address:
          type: string
          description: The restaurant's address
        location:
          type: string
          description: The restaurant's location
        image:
          type: string
          description: The restaurant's image
        reviews:
          type: object
          description: The restaurant's reviews
        company:
          type: integer
          description: The ID of the company that owns the restaurant
